// Common
export const UPDATE_ANY_ERROR = 'UPDATE_ANY_ERROR';

// Get Current Profile
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

// Update MyReservations
export const UPDATE_MY_RESERVATION_REQUEST = 'UPDATE_MY_RESERVATION_REQUEST';
export const UPDATE_MY_RESERVATION_SUCCESS = 'UPDATE_MY_RESERVATION_SUCCESS';
export const UPDATE_MY_RESERVATION_ERROR = 'UPDATE_MY_RESERVATION_ERROR';

// Update MyLunch
export const UPDATE_MY_LUNCH_REQUEST = 'UPDATE_MY_LUNCH_REQUEST';
export const UPDATE_MY_LUNCH_SUCCESS = 'UPDATE_MY_LUNCH_SUCCESS';

// Update Refresh Status
export const UPDATE_REFRESH_STATUS = 'UPDATE_REFRESH_STATUS';

// Update Current Location
export const UPDATE__CURRENT_LOCATION_REQUEST =
  'UPDATE__CURRENT_LOCATION_REQUEST';

// Update My Team
export const UPDATE_MY_TEAM_LIST_REQUEST = 'UPDATE_MY_TEAM_LIST_REQUEST';
export const UPDATE_MY_TEAM_LIST_SUCCESS = 'UPDATE_MY_TEAM_LIST_SUCCESS';
export const UPDATE_MY_TEAM_LIST_ERROR = 'UPDATE_MY_TEAM_LIST_ERROR';

// Update Reservation List Screen Status
export const UPDATE_MY_RESERVATION_STATUS = 'UPDATE_MY_RESERVATION_STATUS';

// Update Current Guest List
export const UPDATE_CURRENT_GUEST_LIST = 'UPDATE_CURRENT_GUEST_LIST';

// Update MyReservations With Current Guest List
export const UPDATE_MY_RESERVATION_WITH_GUESTS =
  'UPDATE_MY_RESERVATION_WITH_GUESTS';

// Refresh Token
export const REFRESH_ID_TOKEN = 'REFRESH_ID_TOKEN';
